server:
  port: ${PORT:5000}
security:
  user:
    password: ${eureka.password}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:5000}/eureka
  
  instance:
      instanceId: ${DOMAIN_NAME:localhost}:${random.value}
      hostname: ${DOMAIN_NAME}
      nonSecurePort: 80